# version: "1"
# projects:
# - name: PHQ
#   environments:
#   - name: private
#     databases:
#     - name: polymarket-hq-pg
#       databaseName: polymarkethq
#       user: masteruser
#       plan: basic-256mb
#       region: frankfurt
#       postgresMajorVersion: "18"
#       diskSizeGB: 1